### ISSUE TITLE
Support for bat file

### ISSUE THREAD

**Issue by FredrikM97** [agowa338/MinecraftSystemdUnit#10]
Is it possible to add support for individual bat files for each server. Lets say that ftb need more ram than a vanilla server and can therefor be regulated from a ServerStart.bat

**Comment by mivalsten** [comment]
systemd is a linux solution, not compatibile with bat/cmd files which are windows specific.

On that note, it would be indeed good to have a configuration file per instance. systemd supports this, so it would be doable.

**Comment by gilesknap** [comment]
I confess that I achieved this by changing the following line:

```ExecStart=/bin/sh -c '/usr/bin/screen -DmS mc-%i ./start_server.sh```

I guess this has significant security issues so I would be interested in the correct solution too.

Having said that I ended up switching to a user service instead of a system one because I found I needed elevated permissions to stop and start the system service and I wanted to give control of minecraft servers to users. Thus the security of start_server.sh file is not much different to the user systemd configuration.

Does anyone have suggestions on how to handle this more securely ?

**Comment by mivalsten** [comment]
Few ways around that.
You can use environment variable in your exec command and supply the value with config script, that way you can have it user editable but not break to many things.
```
Environment="MCMINMEM=512M" "MCMAXMEM=2048M"
EnvironmentFile=/opt/minecraft/%i/server.conf
ExecStart=/bin/sh -c '/usr/bin/screen -DmS mc-%i /usr/bin/java -server -Xms${MCMINMEM} -Xmx${MCMAXMEM} -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(ls -v | grep -i "FTBServer.*jar\|craftbukkit.*jar\|spigot.*jar\|paper*.*jar\|minecraft_server.*jar" | head -n 1) nogui'
```

Then, to change default RAM assignment, you create file /opt/minecraft/survival/server.conf with below contents:
```
MCMINMEM=1024M
MCMAXMEM=3096M
```

source:
https://stackoverflow.com/questions/48934097/using-variable-in-command-path-for-execstart-in-systemd-service

Alternatively, you can edit specific instance with below command:
`sudo systemctl edit minecraft@survival`
That way you can edit ExecStart command of an instance to hardcode memory values for it.

Source: https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services


As for security, you can always grant user a sudo privilage to control that specific service (assuming that username is jane):
```
echo "jane ALL=(root) `which systemctl` start minecraft@survival\n"\
"jane ALL=(root) `which systemctl` stop minecraft@survival\n"\
"jane ALL=(root) `which systemctl` restart minecraft@survival" >> /etc/sudoers.d/jane
```

**Comment by gilesknap** [comment]
Awesome thanks.
