### ISSUE TITLE
Ignoring unknown escape sequence and comments breaking boolean parsing

### ISSUE THREAD

**Issue by yi-fan-song** [agowa338/MinecraftSystemdUnit#12]
1. **Comments**
Inline comments breaks the parsing of the boolean value, it would seem that systemd expects `#` comments to start on a newline.
`ProtectKernelTunables=true # /proc/sys, /sys, /proc/sysrq-trigger, /proc/latency_stats, /proc/acpi, /proc/timer_stats, /proc/fs and /proc/irq will be read-only within the unit. It is recommended to turn this on for most services.`
2.**Unknown escape sequence**
Systemd just removes the backslash in the case of an unknown escape sequence, it processes escape sequences differently from shell. Escaping the backslash seems needed `\\`.
`grep -i "FTBServer.*jar\|craftbukkit.*jar\|spigot.*jar\|paper*.*jar\|minecraft_server.*jar"`

I'm running on ubuntu 20.04 server.

**Comment by TheSageMarmot** [comment]
1. Comments - Thanks for the info! That's a really interesting quark. Arch has also documented it on their wiki. https://wiki.archlinux.org/index.php/systemd#Writing_unit_files
