### ISSUE TITLE
Systemd Ubuntu 20.04 double quotes error

### ISSUE THREAD

**Issue by AntaeusNar** [agowa338/MinecraftSystemdUnit#16]
When running this file in Ubuntu 20.04 the double quotes around the grep options in line 37 prevent grep from working.

I removed the double quotes and it ran just fine.

Not sure if this is a fix, or personal work around.

**Comment by TheSageMarmot** [comment]
I was having the same issue on my Ubuntu 18.04 server, but I didn't know how to fix it. Thank you AntaeusNar

**Comment by joshklod** [comment]
> Not sure if this is a fix, or personal work around.

It's more of a workaround.  See [my comment](https://github.com/agowa338/MinecraftSystemdUnit/pull/17#issuecomment-627650668) on #17 for an explanation, and #18 for a better solution.
