### ISSUE TITLE
Sleep on shutdown

### ISSUE THREAD

**Issue by bram-pkg** [agowa338/MinecraftSystemdUnit#19]
What's the reason that `stop` is immediately run after `save-all`.

Players don't really get the time to read it anyway. I would suggest putting a sleep for 3/5 seconds after the `say` message.

**Comment by agowa** [comment]
On larger worlds with modpacks, the one I initially wrote that for, was so slow, that it took seconds to save and close the world. Therefore it was not really necessary.

**Comment by bram-pkg** [comment]
Did not think of that, you're right. Our world is only around 4GB so saving is basically instant.

**Comment by mivalsten** [comment]
OTOH, you could just implement it as a variable that can be configured along RAM like I did in #15.

**Comment by bramceulemans** [comment]
I'll make a pull request for that later tonight.
