### ISSUE TITLE
Unexpected Server Restarts

### ISSUE THREAD

**Issue by Derp33** [agowa338/MinecraftSystemdUnit#23]
The service restarts the server even on a clean exit with the 'stop' command.
Server versions were Spigot & Paper-1.16.1

journalctl shows this
`minecraft@server.service: Control process exited, code=exited, status=1/FAILURE`

Is it the screen's exit code causing this?  If so, I'm a bit confused, starting the same server with the same screen options exits with 0 :(

**Comment by agowa** [comment]
According to the documentation this is impossible. If "systemctl stop" is causing the non zero exit code the restart should be ignored.
[https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=)

In the given example in this repository on-failure is used. I think there was a bug in systemd a few years ago. It is very hard to tell, could you try to debug it?
You could also have a look into the service logs using journalctl.

**Comment by Derp33** [comment]
Alright, after playing around a bit, I think I found my issue.

`ExecStop` doesn't behave the way I expected it to.  Even if the server stops and the screen exits successfully.  `ExecStop` is always called. So `ExecStop` attempts so send a command to the screen(which will fail because the screen no longer exists).  And so it restarts the server.

I think this is some strange behavior on systemd's part.
1) Process exits successfully.
2) Systemd tells the process to exit.
3) Step 2 failed because the process already exited, I guess I should restart...

Thanks anyway 🙂

**Comment by agowa** [comment]
Interesting. I'd consider that a bug in systemd (or it's documentation) as it says there clearly
> If "systemctl stop" is causing the non zero exit code the restart should be ignored.
