### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by tompointexe** [agowa338/MinecraftSystemdUnit#24]
When starting my minecraft server instance it never starts and systemctl status minecraft@myserver gives me 

`● minecraft@myserver.service - Minecraft Server myserver
     Loaded: loaded (/etc/systemd/system/minecraft@.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2020-07-30 15:25:25 UTC; 47s ago
    Process: 2731 ExecStart=/usr/bin/screen -dmS mc-myserver /usr/bin/java -server -Xms512M -Xmx2048M -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(find -maxdepth 1 -type f -iregex ./\\(FTBServer\\|craftbukkit\\|spigot\|paper\\|forge\\|minecraft_server\\).jar -print0) nogui (code=exited, status=0/SUCCESS)

   Process: 2746 ExecStop=/usr/bin/screen -p 0 -S mc-myserver -X eval stuff "say SERVER SHUTTING DOWN. Saving map..."\015 (code=exited, status=1/FAILURE)
   Main PID: 2731 (code=exited, status=0/SUCCESS)`

I dont know what to do

**Comment by mivalsten** [comment]
Check latest.log first in minecraft directory first to find out why it is
not starting properly. Also, try running the launch command manually. Go to
minecraft directory and issue ` /usr/bin/java -server -Xms512M -Xmx2048M
-XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2
-XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(find -maxdepth 1
-type f -iregex
./\(FTBServer\|craftbukkit\|spigot|paper\|forge\|minecraft_server\).jar
-print0) nogui `

Also, remember to do `sudo systemctl enable minecraft@myserver`

czw., 30 lip 2020 o 17:29 Tom <notifications@github.com> napisał(a):

**Comment by mivalsten** [comment]
Check latest.log first in minecraft directory first to find out why it is not starting properly. Also, try running the launch command manually. Go to minecraft directory and issue `/usr/bin/java -server -Xms512M -Xmx2048M -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(find -maxdepth 1 -type f -iregex ./\(FTBServer\|craftbukkit\|spigot|paper\|forge\|minecraft_server\).jar -print0) nogui`

Also, remember to do `sudo systemctl enable minecraft@myserver`

**Comment by tompointexe** [comment]
> Check latest.log first in minecraft directory first to find out why it is not starting properly. Also, try running the launch command manually. Go to minecraft directory and issue `/usr/bin/java -server -Xms512M -Xmx2048M -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -jar $(find -maxdepth 1 -type f -iregex ./\(FTBServer\|craftbukkit\|spigot|paper\|forge\|minecraft_server\).jar -print0) nogui`
> 
> Also, remember to do `sudo systemctl enable minecraft@myserver`

ok i'l try all that 👍
