### ISSUE TITLE
Aikar's flags

### ISSUE THREAD

**Issue by n0toose** [agowa338/MinecraftSystemdUnit#33]
I would like to continue using the upstream version of this repository for my own purposes, however, I see that many of the JVM flags that I normally used are not... really existing here. I am relatively lazy about it, so, I just blindly use Aikar's Flags, as recommended by the PaperMC docs: https://docs.papermc.io/paper/aikars-flags

Did the flags in the document all get considered already, or is there still space for additional improvement?

**Comment by agowa** [comment]
This project is targeting beginners. Playing with JVM flags is however an advanced user thing to optimize performance.
Also this project support a bunch of different server implementations.
So if you have some flags that you tested and are working for all of them just open a PR and provide a short statement for why to add each of the flags.
(Also flags change as you can see in the commit and PR history).

**Comment by n0toose** [comment]
Ok! Will reopen this issue if necessary. (I may also follow up on here -- even after I've closed it.)
