### ISSUE TITLE
Daemons using outdated libraries

### ISSUE THREAD

**Issue by Subnet-Masked** [agowa338/MinecraftSystemdUnit#5]
Hello, I recently started using your awesome startup script on my server to run a few Minecraft servers.
Recently when I have been trying to install or modify applications via APT, however, I have been getting a message from SystemD indicating that some daemons need to be restarted because they are using outdated libraries.
![Capture](https://user-images.githubusercontent.com/55600371/70814563-b6112480-1d99-11ea-95d0-0cb70b773778.PNG)

I have looked into the service file and do not see any glaring issues, but I am also not very familiar with SystemD...

I am running Debian 10.

If I chose not to restart the services by unselecting them, I am unable to install applications properly.

**Comment by agowa** [comment]
You may installed an update to a newer java version. Just stop your server install updates and restart.
There is nothing that could be done about that.
(Ok, you could move your server into a k8s cluster but even than you would have to deploy a newer container and therefore restart the application)
