### ISSUE TITLE
"minecraft" user inaccessable

### ISSUE THREAD

**Issue by Silent-Hunter** [agowa338/MinecraftSystemdUnit#7]
I can't check on the server, because `su -c "/usr/bin/screen -r" minecraft` asks for a password, even though I never set one for the "minecraft" user.

Is there anything I can do about this?

**Comment by agowa** [comment]
`sudo su` first, than you can su switch to whatever user you'd like.
or just:
`sudo su -c "/usr/bin/screen -r" minecraft` and enter your root password (or sudoers user password depending on your /etc/sudoers configuration)
